# Generated by Django 5.1.4 on 2024-12-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_nari_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='images/')),
            ],
        ),
    ]
