# Generated by Django 5.1.4 on 2024-12-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
