# Generated by Django 5.1.4 on 2024-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
