# Generated by Django 5.1.4 on 2024-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='text',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
