# Generated by Django 5.1.4 on 2024-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_circle_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
    ]
