# Generated by Django 5.1.4 on 2024-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_p2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('images', models.FileField(upload_to='images/')),
            ],
        ),
    ]
