# Generated by Django 5.1.4 on 2024-12-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='img',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
