# Generated by Django 5.1.4 on 2024-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_mobile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('no', models.CharField(blank=True, max_length=11)),
                ('passw', models.CharField(blank=True, max_length=12)),
                ('cartname', models.CharField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=1000)),
                ('discount', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
