# Generated by Django 5.1.4 on 2024-12-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cartname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='passw',
        ),
        migrations.RemoveField(
            model_name='account',
            name='price',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='no',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='members.account')),
            ],
        ),
    ]
