# Generated by Django 5.1.4 on 2025-01-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_cart_account_remove_cart_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
