# Generated by Django 5.1.4 on 2025-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_cart_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.URLField(),
        ),
    ]
