# Generated by Django 5.1.4 on 2025-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_cart_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('images', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
