# Generated by Django 5.1.4 on 2025-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_product3_alter_cart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='discription',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
